info:
  version: 1.0.0
  title: Wallet API
  description: Wallet API definitions
paths:
  /status:
    get:
      responses:
        "200":
          description: success
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
          headers:
            content-security-policy:
              schema:
                type: string
              example: "default-src 'self';base-uri 'self';block-all-mixed-content;font-src
                'self' https: data:;form-action 'self';frame-ancestors
                'self';img-src 'self' data:;object-src 'none';script-src
                'self';script-src-attr 'none';style-src 'self' https:
                'unsafe-inline';upgrade-insecure-requests"
            cross-origin-embedder-policy:
              schema:
                type: string
              example: require-corp
            cross-origin-opener-policy:
              schema:
                type: string
              example: same-origin
            cross-origin-resource-policy:
              schema:
                type: string
              example: same-origin
            x-dns-prefetch-control:
              schema:
                type: string
              example: off
            expect-ct:
              schema:
                type: string
              example: max-age=0
            x-frame-options:
              schema:
                type: string
              example: SAMEORIGIN
            strict-transport-security:
              schema:
                type: string
              example: max-age=15552000; includeSubDomains
            x-download-options:
              schema:
                type: string
              example: noopen
            x-content-type-options:
              schema:
                type: string
              example: nosniff
            origin-agent-cluster:
              schema:
                type: string
              example: ?1
            x-permitted-cross-domain-policies:
              schema:
                type: string
              example: none
            referrer-policy:
              schema:
                type: string
              example: no-referrer
            x-xss-protection:
              schema:
                type: string
              example: "0"
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "15"
            etag:
              schema:
                type: string
              example: W/"f-NQVRlQfKHCoInEbhALgECMonhCE"
            x-response-time:
              schema:
                type: string
              example: 0.737ms
            date:
              schema:
                type: string
              example: Thu, 14 Apr 2022 13:41:59 GMT
            connection:
              schema:
                type: string
              example: close
      tags:
        - Readiness
  /wallets:
    post:
      responses:
        "201":
          description: success
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 55809
          headers:
            content-security-policy:
              schema:
                type: string
              example: "default-src 'self';base-uri 'self';block-all-mixed-content;font-src
                'self' https: data:;form-action 'self';frame-ancestors
                'self';img-src 'self' data:;object-src 'none';script-src
                'self';script-src-attr 'none';style-src 'self' https:
                'unsafe-inline';upgrade-insecure-requests"
            cross-origin-embedder-policy:
              schema:
                type: string
              example: require-corp
            cross-origin-opener-policy:
              schema:
                type: string
              example: same-origin
            cross-origin-resource-policy:
              schema:
                type: string
              example: same-origin
            x-dns-prefetch-control:
              schema:
                type: string
              example: off
            expect-ct:
              schema:
                type: string
              example: max-age=0
            x-frame-options:
              schema:
                type: string
              example: SAMEORIGIN
            strict-transport-security:
              schema:
                type: string
              example: max-age=15552000; includeSubDomains
            x-download-options:
              schema:
                type: string
              example: noopen
            x-content-type-options:
              schema:
                type: string
              example: nosniff
            origin-agent-cluster:
              schema:
                type: string
              example: ?1
            x-permitted-cross-domain-policies:
              schema:
                type: string
              example: none
            referrer-policy:
              schema:
                type: string
              example: no-referrer
            x-xss-protection:
              schema:
                type: string
              example: "0"
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "12"
            etag:
              schema:
                type: string
              example: W/"c-EC5ETn88pSaHHvlvi5eogiqC72E"
            x-response-time:
              schema:
                type: string
              example: 2.042ms
            date:
              schema:
                type: string
              example: Thu, 14 Apr 2022 13:41:59 GMT
            connection:
              schema:
                type: string
              example: close
        "400":
          description: invalid headers
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Missing x-credential-id header
          headers:
            content-security-policy:
              schema:
                type: string
              example: "default-src 'self';base-uri 'self';block-all-mixed-content;font-src
                'self' https: data:;form-action 'self';frame-ancestors
                'self';img-src 'self' data:;object-src 'none';script-src
                'self';script-src-attr 'none';style-src 'self' https:
                'unsafe-inline';upgrade-insecure-requests"
            cross-origin-embedder-policy:
              schema:
                type: string
              example: require-corp
            cross-origin-opener-policy:
              schema:
                type: string
              example: same-origin
            cross-origin-resource-policy:
              schema:
                type: string
              example: same-origin
            x-dns-prefetch-control:
              schema:
                type: string
              example: off
            expect-ct:
              schema:
                type: string
              example: max-age=0
            x-frame-options:
              schema:
                type: string
              example: SAMEORIGIN
            strict-transport-security:
              schema:
                type: string
              example: max-age=15552000; includeSubDomains
            x-download-options:
              schema:
                type: string
              example: noopen
            x-content-type-options:
              schema:
                type: string
              example: nosniff
            origin-agent-cluster:
              schema:
                type: string
              example: ?1
            x-permitted-cross-domain-policies:
              schema:
                type: string
              example: none
            referrer-policy:
              schema:
                type: string
              example: no-referrer
            x-xss-protection:
              schema:
                type: string
              example: "0"
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "44"
            etag:
              schema:
                type: string
              example: W/"2c-e6XhgGuaKdfKWUScDV0tXRE2iAI"
            x-response-time:
              schema:
                type: string
              example: 0.506ms
            date:
              schema:
                type: string
              example: Thu, 14 Apr 2022 13:41:59 GMT
            connection:
              schema:
                type: string
              example: close
        "500":
          description: internal error
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Rem ea culpa.
          headers:
            content-security-policy:
              schema:
                type: string
              example: "default-src 'self';base-uri 'self';block-all-mixed-content;font-src
                'self' https: data:;form-action 'self';frame-ancestors
                'self';img-src 'self' data:;object-src 'none';script-src
                'self';script-src-attr 'none';style-src 'self' https:
                'unsafe-inline';upgrade-insecure-requests"
            cross-origin-embedder-policy:
              schema:
                type: string
              example: require-corp
            cross-origin-opener-policy:
              schema:
                type: string
              example: same-origin
            cross-origin-resource-policy:
              schema:
                type: string
              example: same-origin
            x-dns-prefetch-control:
              schema:
                type: string
              example: off
            expect-ct:
              schema:
                type: string
              example: max-age=0
            x-frame-options:
              schema:
                type: string
              example: SAMEORIGIN
            strict-transport-security:
              schema:
                type: string
              example: max-age=15552000; includeSubDomains
            x-download-options:
              schema:
                type: string
              example: noopen
            x-content-type-options:
              schema:
                type: string
              example: nosniff
            origin-agent-cluster:
              schema:
                type: string
              example: ?1
            x-permitted-cross-domain-policies:
              schema:
                type: string
              example: none
            referrer-policy:
              schema:
                type: string
              example: no-referrer
            x-xss-protection:
              schema:
                type: string
              example: "0"
            vary:
              schema:
                type: string
              example: Origin
            content-type:
              schema:
                type: string
              example: application/json; charset=utf-8
            content-length:
              schema:
                type: string
              example: "27"
            etag:
              schema:
                type: string
              example: W/"1b-h1L3L74LBOUBVGh3OX45mWihkdI"
            x-response-time:
              schema:
                type: string
              example: 1.641ms
            date:
              schema:
                type: string
              example: Thu, 14 Apr 2022 13:41:59 GMT
            connection:
              schema:
                type: string
              example: close
      tags:
        - Wallets
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Della
servers:
  - url: http://localhost:6060
    description: Wallet API Server
openapi: 3.0.3
